#import <Foundation/Foundation.h>
#import <CoreImage/CoreImage.h>
#include <atomic>
#include <chrono>
#include <condition_variable>
#include <mutex>
#include <string>
#include <thread>
#include <vector>
#include "TOP_CPlusPlusBase.h"
#include "CPlusPlus_Common.h"
using namespace TD;
namespace {struct Result{std::vector<uint8_t>p;uint32_t w=0,h=0;uint64_t serial=0;};struct Settings{std::string text,type,correction;int width=512,height=512,quiet=4;};class CoreImageCodeTOP final:public TOP_CPlusPlusBase{
public:CoreImageCodeTOP(const OP_NodeInfo*,TOP_Context*c):myContext(c){myThread=std::thread([this]{worker();});}~CoreImageCodeTOP()override{{std::lock_guard<std::mutex>l(myMutex);myQuit=true;}myCond.notify_all();if(myThread.joinable())myThread.join();}void getGeneralInfo(TOP_GeneralInfo*g,const OP_Inputs*,void*)override{g->cookEveryFrameIfAsked=true;}
 void execute(TOP_Output*out,const OP_Inputs*in,void*)override{myExec++;Settings s;s.text=in->getParString("Text")?:"";s.type=in->getParString("Type")?:"qr";s.correction=in->getParString("Correction")?:"M";s.width=std::clamp(in->getParInt("Width"),16,4096);s.height=std::clamp(in->getParInt("Height"),16,4096);s.quiet=std::clamp(in->getParInt("Quietzone"),0,64);std::string sig=s.text+":"+s.type+":"+s.correction+":"+std::to_string(s.width)+":"+std::to_string(s.height)+":"+std::to_string(s.quiet);if(sig!=mySig){mySig=sig;std::lock_guard<std::mutex>l(myMutex);mySettings=s;myPending=true;mySubmit++;myCond.notify_one();}Result r;{std::lock_guard<std::mutex>l(myMutex);if(myResult.serial==myUploaded||myResult.p.empty())return;r=myResult;myUploaded=r.serial;}TOP_UploadInfo ui;ui.textureDesc.texDim=OP_TexDim::e2D;ui.textureDesc.width=r.w;ui.textureDesc.height=r.h;ui.textureDesc.pixelFormat=OP_PixelFormat::BGRA8Fixed;auto b=myContext->createOutputBuffer(r.p.size(),TOP_BufferFlags::None,nullptr);if(!b)return;memcpy(b->data,r.p.data(),r.p.size());out->uploadBuffer(&b,ui,nullptr);}
 void setupParameters(OP_ParameterManager*m,void*)override{OP_StringParameter t("Text");t.label="Text";t.page="Core Image Code";t.defaultValue="TDAppleML";m->appendString(t);OP_StringParameter y("Type");y.label="Code Type";y.page="Core Image Code";y.defaultValue="qr";const char*n[]={"qr","aztec","pdf417","code128"};const char*l[]={"QR Code","Aztec","PDF417","Code 128"};m->appendMenu(y,4,n,l);OP_StringParameter c("Correction");c.label="QR Correction Level";c.page="Core Image Code";c.defaultValue="M";const char*cn[]={"L","M","Q","H"};m->appendMenu(c,4,cn,cn);addInt(m,"Width","Output Width",512,16,4096);addInt(m,"Height","Output Height",512,16,4096);addInt(m,"Quietzone","Quiet Zone",4,0,64);}
 int32_t getNumInfoCHOPChans(void*)override{return 5;}void getInfoCHOPChan(int32_t i,OP_InfoCHOPChan*c,void*)override{const char*n[]={"executes","submits","generates","generate_ms","valid"};float v[]={(float)myExec.load(),(float)mySubmit.load(),(float)myGenerate.load(),myMs.load(),myValid?1.f:0.f};c->name->setString(n[i]);c->value=v[i];}void getWarningString(OP_String*s,void*)override{std::lock_guard<std::mutex>l(myMutex);if(!myWarning.empty())s->setString(myWarning.c_str());}
private:static void addInt(OP_ParameterManager*m,const char*n,const char*l,int d,int lo,int hi){OP_NumericParameter p(n);p.label=l;p.page="Core Image Code";p.defaultValues[0]=d;p.minSliders[0]=lo;p.maxSliders[0]=hi;p.minValues[0]=lo;p.maxValues[0]=hi;p.clampMins[0]=p.clampMaxes[0]=true;m->appendInt(p);}void worker(){while(true){Settings s;{std::unique_lock<std::mutex>l(myMutex);myCond.wait(l,[this]{return myQuit||myPending;});if(myQuit)return;s=mySettings;myPending=false;}Result r;std::string w;auto t=std::chrono::steady_clock::now();bool ok=generate(s,r,w);myMs=std::chrono::duration<float,std::milli>(std::chrono::steady_clock::now()-t).count();myGenerate++;myValid=ok;{std::lock_guard<std::mutex>l(myMutex);if(ok){r.serial=++mySerial;myResult=std::move(r);}myWarning=std::move(w);}}}
 static bool generate(const Settings&s,Result&r,std::string&w){@autoreleasepool{@synchronized([CIFilter class]){NSString*name=@"CIQRCodeGenerator";if(s.type=="aztec")name=@"CIAztecCodeGenerator";else if(s.type=="pdf417")name=@"CIPDF417BarcodeGenerator";else if(s.type=="code128")name=@"CICode128BarcodeGenerator";CIFilter*f=[CIFilter filterWithName:name];NSData*d=[[NSString stringWithUTF8String:s.text.c_str()] dataUsingEncoding:NSUTF8StringEncoding];[f setValue:d forKey:@"inputMessage"];if(s.type=="qr")[f setValue:[NSString stringWithUTF8String:s.correction.c_str()] forKey:@"inputCorrectionLevel"];if(s.type=="code128")[f setValue:@(s.quiet) forKey:@"inputQuietSpace"];CIImage*code=f.outputImage;if(!code){w="Code generator rejected the text or settings";return false;}CGRect ce=code.extent;CGFloat q=s.type=="code128"?0:s.quiet;CGFloat sx=floor((s.width-2*q)/ce.size.width),sy=floor((s.height-2*q)/ce.size.height),scale=std::max<CGFloat>(1,std::min(sx,sy));CIImage*scaled=[code imageByApplyingTransform:CGAffineTransformMakeScale(scale,scale)];CGFloat ox=floor((s.width-scaled.extent.size.width)/2),oy=floor((s.height-scaled.extent.size.height)/2);scaled=[scaled imageByApplyingTransform:CGAffineTransformMakeTranslation(ox,oy)];CIImage*white=[[CIImage imageWithColor:[CIColor colorWithRed:1 green:1 blue:1 alpha:1]] imageByCroppingToRect:CGRectMake(0,0,s.width,s.height)];scaled=[scaled imageByCompositingOverImage:white];r.w=s.width;r.h=s.height;r.p.resize((size_t)r.w*r.h*4);CGColorSpaceRef cs=CGColorSpaceCreateDeviceRGB();[[CIContext contextWithOptions:@{kCIContextUseSoftwareRenderer:@NO}] render:scaled toBitmap:r.p.data() rowBytes:r.w*4 bounds:CGRectMake(0,0,r.w,r.h) format:kCIFormatBGRA8 colorSpace:cs];CGColorSpaceRelease(cs);return true;}}}
 TOP_Context*myContext;std::thread myThread;std::condition_variable myCond;std::mutex myMutex;bool myQuit=false,myPending=false;Settings mySettings;Result myResult;std::string mySig,myWarning;uint64_t mySerial=0,myUploaded=0;std::atomic<uint64_t>myExec{0},mySubmit{0},myGenerate{0};std::atomic<float>myMs{0};std::atomic<bool>myValid{false};};}
extern "C"{DLLEXPORT void FillTOPPluginInfo(TOP_PluginInfo*i){if(!i->setAPIVersion(TOPCPlusPlusAPIVersion))return;i->executeMode=TOP_ExecuteMode::CPUMem;i->customOPInfo.opType->setString("Cicode");i->customOPInfo.opLabel->setString("CI Code");i->customOPInfo.opIcon->setString("CIC");if(i->customOPInfo.opHelpURL)i->customOPInfo.opHelpURL->setString("https://github.com/sygnalinc/Apple-Frameworks-for-TouchDesigner/blob/main/CoreImageCode/README.md");i->customOPInfo.authorName->setString("SYGNAL Inc.");
i->customOPInfo.majorVersion = 0;
i->customOPInfo.minorVersion = 9;i->customOPInfo.minInputs=0;i->customOPInfo.maxInputs=0;}DLLEXPORT TOP_CPlusPlusBase*CreateTOPInstance(const OP_NodeInfo*i,TOP_Context*c){return new CoreImageCodeTOP(i,c);}DLLEXPORT void DestroyTOPInstance(TOP_CPlusPlusBase*i,TOP_Context*){delete static_cast<CoreImageCodeTOP*>(i);}}
