// MPSAnalyze CHOP — Metal Performance Shaders histogram + image statistics.
#import <Foundation/Foundation.h>
#import <Metal/Metal.h>
#import <MetalPerformanceShaders/MetalPerformanceShaders.h>
#include <algorithm>
#include <atomic>
#include <chrono>
#include <cmath>
#include <condition_variable>
#include <mutex>
#include <string>
#include <thread>
#include <vector>
#include "CHOP_CPlusPlusBase.h"
#include "CPlusPlus_Common.h"
using namespace TD;
namespace {
constexpr int kBins=16,kStats=12,kChannels=kStats+kBins*4;
struct Result{float v[kChannels]={};};
class MPSAnalyzeCHOP final:public CHOP_CPlusPlusBase{
public:MPSAnalyzeCHOP(const OP_NodeInfo*){myDevice=MTLCreateSystemDefaultDevice();if(myDevice)myQueue=[myDevice newCommandQueue];myThread=std::thread([this]{worker();});}~MPSAnalyzeCHOP()override{{std::lock_guard<std::mutex>l(myMutex);myQuit=true;}myCond.notify_all();if(myThread.joinable())myThread.join();myQueue=nil;myDevice=nil;}void getGeneralInfo(CHOP_GeneralInfo*g,const OP_Inputs*,void*)override{g->cookEveryFrameIfAsked=true;g->timeslice=false;}bool getOutputInfo(CHOP_OutputInfo*i,const OP_Inputs*,void*)override{i->numChannels=kChannels;i->numSamples=1;i->startIndex=0;return true;}
 void getChannelName(int32_t i,OP_String*n,const OP_Inputs*,void*)override{const char*s[]={"valid","mean_r","mean_g","mean_b","mean_a","mean_luma","std_luma","min_luma","max_luma","dark","midtone","bright"};if(i<kStats){n->setString(s[i]);return;}int x=i-kStats,c=x/kBins,b=x%kBins;const char*ch[]={"r","g","b","a"};char z[32];snprintf(z,sizeof(z),"hist_%s%d",ch[c],b);n->setString(z);}
 void execute(CHOP_Output*out,const OP_Inputs*in,void*)override{myExec++;bool active=in->getParInt("Active")!=0,flip=in->getParInt("Flip")!=0;int flipSig=flip?1:0;if(flipSig!=myFlipSig){myFlipSig=flipSig;myLast=-1;}const OP_TOPInput*top=in->getParTOP("Top");if(active&&top&&(int64_t)top->totalCooks!=myLast){std::unique_lock<std::mutex>l(myMutex,std::try_to_lock);if(l.owns_lock()&&!myPending&&!myBusy){OP_TOPInputDownloadOptions o;o.pixelFormat=OP_PixelFormat::BGRA8Fixed;o.verticalFlip=flip;myDownload=top->downloadTexture(o,nullptr);if(myDownload){myPending=true;myLast=top->totalCooks;mySubmit++;l.unlock();myCond.notify_one();}}}Result r;{std::lock_guard<std::mutex>l(myMutex);r=myResult;}for(int i=0;i<kChannels;i++)out->channels[i][0]=active?r.v[i]:0;}
 void setupParameters(OP_ParameterManager*m,void*)override{OP_StringParameter t("Top");t.label="TOP";t.page="MPS Analyze";m->appendTOP(t);OP_NumericParameter a("Active");a.label="Active";a.page="MPS Analyze";a.defaultValues[0]=1;m->appendToggle(a);OP_NumericParameter f("Flip");f.label="Flip Image Vertically";f.page="MPS Analyze";f.defaultValues[0]=1;m->appendToggle(f);}
 int32_t getNumInfoCHOPChans(void*)override{return 5;}void getInfoCHOPChan(int32_t i,OP_InfoCHOPChan*c,void*)override{const char*n[]={"executes","submits","analyzes","analyze_ms","pixels"};float v[]={(float)myExec.load(),(float)mySubmit.load(),(float)myAnalyze.load(),myMs.load(),(float)myPixels.load()};c->name->setString(n[i]);c->value=v[i];}void getWarningString(OP_String*s,void*)override{std::lock_guard<std::mutex>l(myMutex);if(!myWarning.empty())s->setString(myWarning.c_str());}
private:
 void worker(){while(true){OP_SmartRef<OP_TOPDownloadResult>d;{std::unique_lock<std::mutex>l(myMutex);myCond.wait(l,[this]{return myQuit||myPending;});if(myQuit)return;d=std::move(myDownload);myPending=false;myBusy=true;}Result r;std::string w;auto t=std::chrono::steady_clock::now();bool ok=analyze(d,r,w);myMs=std::chrono::duration<float,std::milli>(std::chrono::steady_clock::now()-t).count();myAnalyze++;{std::lock_guard<std::mutex>l(myMutex);myResult=ok?r:Result{};myWarning=std::move(w);myBusy=false;}}}
 bool analyze(OP_SmartRef<OP_TOPDownloadResult>&d,Result&r,std::string&w){if(!myDevice||!myQueue){w="Metal device unavailable";return false;}void*data=d->getData();uint32_t width=d->textureDesc.width,height=d->textureDesc.height;if(!data||!width||!height)return false;@autoreleasepool{MTLTextureDescriptor*desc=[MTLTextureDescriptor texture2DDescriptorWithPixelFormat:MTLPixelFormatBGRA8Unorm width:width height:height mipmapped:NO];desc.storageMode=MTLStorageModeShared;desc.usage=MTLTextureUsageShaderRead;id<MTLTexture>tex=[myDevice newTextureWithDescriptor:desc];if(!tex)return false;[tex replaceRegion:MTLRegionMake2D(0,0,width,height) mipmapLevel:0 withBytes:data bytesPerRow:width*4];MPSImageHistogramInfo info{};info.numberOfHistogramEntries=256;info.histogramForAlpha=YES;info.minPixelValue=(vector_float4){0,0,0,0};info.maxPixelValue=(vector_float4){1,1,1,1};MPSImageHistogram*hist=[[MPSImageHistogram alloc]initWithDevice:myDevice histogramInfo:&info];NSUInteger bytes=[hist histogramSizeForSourceFormat:tex.pixelFormat];id<MTLBuffer>buf=[myDevice newBufferWithLength:bytes options:MTLResourceStorageModeShared];id<MTLCommandBuffer>cmd=[myQueue commandBuffer];[hist encodeToCommandBuffer:cmd sourceTexture:tex histogram:buf histogramOffset:0];[cmd commit];[cmd waitUntilCompleted];if(cmd.error){w=cmd.error.localizedDescription.UTF8String?:"MPS histogram failed";return false;}uint32_t*h=(uint32_t*)buf.contents;uint64_t pixels=(uint64_t)width*height;myPixels=pixels;if(!h||!pixels)return false;r.v[0]=1;for(int c=0;c<4;c++){double sum=0;for(int b=0;b<256;b++)sum+=h[c*256+b]*(b/255.0);r.v[1+c]=sum/pixels;for(int k=0;k<kBins;k++){uint64_t count=0;for(int b=k*16;b<(k+1)*16;b++)count+=h[c*256+b];r.v[kStats+c*kBins+k]=(float)count/pixels;}}
  uint8_t*p=(uint8_t*)data;double sum=0,sum2=0;float mn=1,mx=0;uint64_t dark=0,mid=0,bright=0;for(uint64_t i=0;i<pixels;i++){float y=(.0722f*p[i*4]+.7152f*p[i*4+1]+.2126f*p[i*4+2])/255.f;sum+=y;sum2+=y*y;mn=std::min(mn,y);mx=std::max(mx,y);if(y<.25f)dark++;else if(y>.75f)bright++;else mid++;}double mean=sum/pixels;r.v[5]=mean;r.v[6]=sqrt(std::max(0.0,sum2/pixels-mean*mean));r.v[7]=mn;r.v[8]=mx;r.v[9]=(float)dark/pixels;r.v[10]=(float)mid/pixels;r.v[11]=(float)bright/pixels;return true;}}
 id<MTLDevice>myDevice=nil;id<MTLCommandQueue>myQueue=nil;std::thread myThread;std::condition_variable myCond;std::mutex myMutex;bool myQuit=false,myPending=false,myBusy=false;OP_SmartRef<OP_TOPDownloadResult>myDownload;Result myResult;std::string myWarning;int64_t myLast=-1;int myFlipSig=-1;std::atomic<uint64_t>myExec{0},mySubmit{0},myAnalyze{0},myPixels{0};std::atomic<float>myMs{0};};}
extern "C"{DLLEXPORT void FillCHOPPluginInfo(CHOP_PluginInfo*i){if(!i->setAPIVersion(CHOPCPlusPlusAPIVersion))return;i->customOPInfo.opType->setString("Metalmpsanalyze");i->customOPInfo.opLabel->setString("Metal MPS Analyze");i->customOPInfo.opIcon->setString("MPS");i->customOPInfo.authorName->setString("TDAppleML");i->customOPInfo.minInputs=0;i->customOPInfo.maxInputs=0;}DLLEXPORT CHOP_CPlusPlusBase*CreateCHOPInstance(const OP_NodeInfo*i){return new MPSAnalyzeCHOP(i);}DLLEXPORT void DestroyCHOPInstance(CHOP_CPlusPlusBase*i){delete static_cast<MPSAnalyzeCHOP*>(i);}}
