// VisionBokeh TOP — grayscale maskで制御するCore Image可変ぼかし。
#import <Foundation/Foundation.h>
#import <CoreImage/CoreImage.h>
#include <atomic>
#include <chrono>
#include <condition_variable>
#include <cstring>
#include <mutex>
#include <string>
#include <thread>
#include <vector>
#include "TOP_CPlusPlusBase.h"
#include "CPlusPlus_Common.h"
using namespace TD;
namespace {
struct Result{std::vector<uint8_t>p;uint32_t w=0,h=0;uint64_t serial=0;};
class VisionBokehTOP final:public TOP_CPlusPlusBase{
public:VisionBokehTOP(const OP_NodeInfo*,TOP_Context*c):myContext(c){myThread=std::thread([this]{worker();});}~VisionBokehTOP()override{{std::lock_guard<std::mutex>l(myMutex);myQuit=true;}myCond.notify_all();if(myThread.joinable())myThread.join();}void getGeneralInfo(TOP_GeneralInfo*g,const OP_Inputs*,void*)override{g->cookEveryFrameIfAsked=true;}
 void execute(TOP_Output*out,const OP_Inputs*in,void*)override{myExec++;bool active=in->getParInt("Active")!=0,flip=in->getParInt("Flip")!=0,invert=in->getParInt("Background")!=0;float radius=std::clamp((float)in->getParDouble("Radius"),0.f,100.f);std::string sig=std::to_string(radius)+(invert?":1":":0")+(flip?":1":":0");if(sig!=mySig){mySig=sig;myLastA=myLastM=-1;}const OP_TOPInput*a=in->getInputTOP(0),*m=in->getInputTOP(1);if(active&&a&&m&&((int64_t)a->totalCooks!=myLastA||(int64_t)m->totalCooks!=myLastM)){std::unique_lock<std::mutex>l(myMutex,std::try_to_lock);if(l.owns_lock()&&!myPending&&!myBusy){OP_TOPInputDownloadOptions o;o.pixelFormat=OP_PixelFormat::BGRA8Fixed;o.verticalFlip=flip;myImage=a->downloadTexture(o,nullptr);myMask=m->downloadTexture(o,nullptr);if(myImage&&myMask){myRadius=radius;myInvert=invert;myPending=true;myLastA=a->totalCooks;myLastM=m->totalCooks;mySubmit++;l.unlock();myCond.notify_one();}}}Result r;{std::lock_guard<std::mutex>l(myMutex);if(myResult.serial==myUploaded||myResult.p.empty())return;r=myResult;myUploaded=r.serial;}TOP_UploadInfo ui;ui.textureDesc.texDim=OP_TexDim::e2D;ui.textureDesc.width=r.w;ui.textureDesc.height=r.h;ui.textureDesc.pixelFormat=OP_PixelFormat::BGRA8Fixed;auto b=myContext->createOutputBuffer(r.p.size(),TOP_BufferFlags::None,nullptr);if(!b)return;memcpy(b->data,r.p.data(),r.p.size());out->uploadBuffer(&b,ui,nullptr);}
 void setupParameters(OP_ParameterManager*m,void*)override{OP_NumericParameter a("Active");a.label="Active";a.page="Vision Bokeh";a.defaultValues[0]=1;m->appendToggle(a);OP_NumericParameter r("Radius");r.label="Blur Radius";r.page="Vision Bokeh";r.defaultValues[0]=20;r.minSliders[0]=0;r.maxSliders[0]=50;r.minValues[0]=0;r.maxValues[0]=100;r.clampMins[0]=r.clampMaxes[0]=true;m->appendFloat(r);OP_NumericParameter b("Background");b.label="Blur Background (Invert Mask)";b.page="Vision Bokeh";b.defaultValues[0]=1;m->appendToggle(b);OP_NumericParameter f("Flip");f.label="Flip Image Vertically";f.page="Vision Bokeh";f.defaultValues[0]=1;m->appendToggle(f);}
 int32_t getNumInfoCHOPChans(void*)override{return 5;}void getInfoCHOPChan(int32_t i,OP_InfoCHOPChan*c,void*)override{const char*n[]={"executes","submits","processes","process_ms","valid"};float v[]={(float)myExec.load(),(float)mySubmit.load(),(float)myProcess.load(),myMs.load(),myValid?1.f:0.f};c->name->setString(n[i]);c->value=v[i];}void getWarningString(OP_String*s,void*)override{std::lock_guard<std::mutex>l(myMutex);if(!myWarning.empty())s->setString(myWarning.c_str());}
private:
 void worker(){while(true){OP_SmartRef<OP_TOPDownloadResult>a,m;float radius;bool invert;{std::unique_lock<std::mutex>l(myMutex);myCond.wait(l,[this]{return myQuit||myPending;});if(myQuit)return;a=std::move(myImage);m=std::move(myMask);radius=myRadius;invert=myInvert;myPending=false;myBusy=true;}Result r;std::string w;auto t=std::chrono::steady_clock::now();bool ok=process(a,m,radius,invert,r,w);myMs=std::chrono::duration<float,std::milli>(std::chrono::steady_clock::now()-t).count();myProcess++;myValid=ok;{std::lock_guard<std::mutex>l(myMutex);if(ok){r.serial=++mySerial;myResult=std::move(r);}myWarning=std::move(w);myBusy=false;}}}
 static CIImage*makeImage(OP_SmartRef<OP_TOPDownloadResult>&d,CGColorSpaceRef cs){void*p=d->getData();uint32_t w=d->textureDesc.width,h=d->textureDesc.height;if(!p||!w||!h)return nil;NSData*data=[NSData dataWithBytes:p length:(size_t)w*h*4];return[CIImage imageWithBitmapData:data bytesPerRow:w*4 size:CGSizeMake(w,h) format:kCIFormatBGRA8 colorSpace:cs];}
 static bool process(OP_SmartRef<OP_TOPDownloadResult>&a,OP_SmartRef<OP_TOPDownloadResult>&m,float radius,bool invert,Result&r,std::string&w){@autoreleasepool{@synchronized([CIFilter class]){uint32_t iw=a->textureDesc.width,ih=a->textureDesc.height;if(!iw||!ih)return false;CGColorSpaceRef cs=CGColorSpaceCreateDeviceRGB();CIImage*image=makeImage(a,cs),*mask=makeImage(m,cs);if(!image||!mask){CGColorSpaceRelease(cs);return false;}CGRect e=image.extent;if(mask.extent.size.width!=e.size.width||mask.extent.size.height!=e.size.height){CGFloat sx=e.size.width/mask.extent.size.width,sy=e.size.height/mask.extent.size.height;mask=[mask imageByApplyingTransform:CGAffineTransformMakeScale(sx,sy)];}if(invert){CIFilter*inv=[CIFilter filterWithName:@"CIColorInvert"];[inv setValue:mask forKey:kCIInputImageKey];mask=inv.outputImage;}CIFilter*f=[CIFilter filterWithName:@"CIMaskedVariableBlur"];[f setValue:image forKey:kCIInputImageKey];[f setValue:mask forKey:@"inputMask"];[f setValue:@(radius) forKey:kCIInputRadiusKey];CIImage*o=[f.outputImage imageByCroppingToRect:e];if(!o){CGColorSpaceRelease(cs);w="Masked variable blur produced no image";return false;}r.w=iw;r.h=ih;r.p.resize((size_t)iw*ih*4);CIContext*ctx=[CIContext contextWithOptions:@{kCIContextUseSoftwareRenderer:@NO}];[ctx render:o toBitmap:r.p.data() rowBytes:iw*4 bounds:e format:kCIFormatBGRA8 colorSpace:cs];std::vector<uint8_t>row((size_t)iw*4);for(uint32_t y=0;y<ih/2;y++){uint8_t*x=r.p.data()+(size_t)y*iw*4;uint8_t*z=r.p.data()+(size_t)(ih-1-y)*iw*4;memcpy(row.data(),x,row.size());memcpy(x,z,row.size());memcpy(z,row.data(),row.size());}CGColorSpaceRelease(cs);return true;}}}
 TOP_Context*myContext;std::thread myThread;std::condition_variable myCond;std::mutex myMutex;bool myQuit=false,myPending=false,myBusy=false;OP_SmartRef<OP_TOPDownloadResult>myImage,myMask;float myRadius=20;bool myInvert=true;Result myResult;std::string myWarning,mySig;int64_t myLastA=-1,myLastM=-1;uint64_t mySerial=0,myUploaded=0;std::atomic<uint64_t>myExec{0},mySubmit{0},myProcess{0};std::atomic<float>myMs{0};std::atomic<bool>myValid{false};};}
extern "C"{DLLEXPORT void FillTOPPluginInfo(TOP_PluginInfo*i){if(!i->setAPIVersion(TOPCPlusPlusAPIVersion))return;i->executeMode=TOP_ExecuteMode::CPUMem;i->customOPInfo.opType->setString("Coreimagebokeh");i->customOPInfo.opLabel->setString("CI Bokeh");i->customOPInfo.opIcon->setString("CIB");if(i->customOPInfo.opHelpURL)i->customOPInfo.opHelpURL->setString("https://github.com/sygnalinc/TDAppleOps/blob/main/CoreImageBokeh/README.md");i->customOPInfo.authorName->setString("SYGNAL Inc.");i->customOPInfo.minInputs=2;i->customOPInfo.maxInputs=2;}DLLEXPORT TOP_CPlusPlusBase*CreateTOPInstance(const OP_NodeInfo*i,TOP_Context*c){return new VisionBokehTOP(i,c);}DLLEXPORT void DestroyTOPInstance(TOP_CPlusPlusBase*i,TOP_Context*){delete static_cast<VisionBokehTOP*>(i);}}
