// ScreenCapture TOP — ScreenCaptureKitによるdisplay/window取り込み。
#import <Foundation/Foundation.h>
#import <ScreenCaptureKit/ScreenCaptureKit.h>
#import <CoreVideo/CoreVideo.h>
#include <atomic>
#include <mutex>
#include <string>
#include <vector>
#include "TOP_CPlusPlusBase.h"
#include "CPlusPlus_Common.h"
using namespace TD;
namespace { class ScreenCaptureTOP; }
@interface TDScreenCaptureOutput:NSObject<SCStreamOutput,SCStreamDelegate>@property(nonatomic,assign)void*owner;@end
namespace {
struct Frame{std::vector<uint8_t>p;uint32_t w=0,h=0;uint64_t serial=0;};
class ScreenCaptureTOP final:public TOP_CPlusPlusBase{
public:
 ScreenCaptureTOP(const OP_NodeInfo*,TOP_Context*c):myContext(c){myOutput=[TDScreenCaptureOutput new];myOutput.owner=this;}
 ~ScreenCaptureTOP()override{myOutput.owner=nullptr;if(myStream)[myStream stopCaptureWithCompletionHandler:^(NSError*){}];myStream=nil;myOutput=nil;}
 void getGeneralInfo(TOP_GeneralInfo*g,const OP_Inputs*,void*)override{g->cookEveryFrameIfAsked=true;}
 void execute(TOP_Output*out,const OP_Inputs*in,void*)override{myExec++;bool active=in->getParInt("Active")!=0;std::string mode=in->getParString("Mode")?:"display";int index=std::max(0,in->getParInt("Index")),w=std::max(0,in->getParInt("Width")),h=std::max(0,in->getParInt("Height")),fps=std::clamp(in->getParInt("Fps"),1,120);bool cursor=in->getParInt("Cursor")!=0;std::string sig=mode+":"+std::to_string(index)+":"+std::to_string(w)+":"+std::to_string(h)+":"+std::to_string(fps)+(cursor?":1":":0");if(active&&sig!=mySig&&!myStarting){mySig=sig;start(mode,index,w,h,fps,cursor);}if(!active&&myStream){[myStream stopCaptureWithCompletionHandler:^(NSError*){}];myStream=nil;myRunning=false;}
  Frame f;{std::lock_guard<std::mutex>l(myMutex);if(myFrame.serial==myUploaded||myFrame.p.empty())return;f=myFrame;myUploaded=f.serial;}TOP_UploadInfo ui;ui.textureDesc.texDim=OP_TexDim::e2D;ui.textureDesc.width=f.w;ui.textureDesc.height=f.h;ui.textureDesc.pixelFormat=OP_PixelFormat::BGRA8Fixed;auto b=myContext->createOutputBuffer(f.p.size(),TOP_BufferFlags::None,nullptr);if(!b)return;memcpy(b->data,f.p.data(),f.p.size());out->uploadBuffer(&b,ui,nullptr);}
 void setupParameters(OP_ParameterManager*m,void*)override{OP_NumericParameter a("Active");a.label="Active";a.page="Screen Capture";a.defaultValues[0]=1;m->appendToggle(a);OP_StringParameter mode("Mode");mode.label="Source Type";mode.page="Screen Capture";mode.defaultValue="display";const char*n[]={"display","window"};const char*l[]={"Display","Window"};m->appendMenu(mode,2,n,l);addInt(m,"Index","Source Index",0,0,100);addInt(m,"Width","Output Width (0=Native)",0,0,7680);addInt(m,"Height","Output Height (0=Native)",0,0,4320);addInt(m,"Fps","Frame Rate",60,1,120);OP_NumericParameter c("Cursor");c.label="Show Cursor";c.page="Screen Capture";c.defaultValues[0]=1;m->appendToggle(c);OP_NumericParameter r("Restart");r.label="Restart Capture";r.page="Screen Capture";m->appendPulse(r);}
 void pulsePressed(const char*n,void*)override{if(!strcmp(n,"Restart")){mySig.clear();if(myStream){[myStream stopCaptureWithCompletionHandler:^(NSError*){}];myStream=nil;myRunning=false;}}}
 int32_t getNumInfoCHOPChans(void*)override{return 6;}void getInfoCHOPChan(int32_t i,OP_InfoCHOPChan*c,void*)override{const char*n[]={"executes","frames","running","sources","width","height"};float v[]={(float)myExec.load(),(float)myFrames.load(),myRunning?1.f:0.f,(float)mySources.load(),(float)myLastW.load(),(float)myLastH.load()};c->name->setString(n[i]);c->value=v[i];}void getWarningString(OP_String*s,void*)override{std::lock_guard<std::mutex>l(myMutex);if(!myWarning.empty())s->setString(myWarning.c_str());}
 void receive(CMSampleBufferRef sample){CVImageBufferRef px=CMSampleBufferGetImageBuffer(sample);if(!px)return;CVPixelBufferLockBaseAddress(px,kCVPixelBufferLock_ReadOnly);uint32_t w=CVPixelBufferGetWidth(px),h=CVPixelBufferGetHeight(px);size_t stride=CVPixelBufferGetBytesPerRow(px);uint8_t*src=(uint8_t*)CVPixelBufferGetBaseAddress(px);Frame f;f.w=w;f.h=h;f.p.resize((size_t)w*h*4);if(src)for(uint32_t y=0;y<h;y++)memcpy(f.p.data()+(size_t)(h-1-y)*w*4,src+(size_t)y*stride,w*4);CVPixelBufferUnlockBaseAddress(px,kCVPixelBufferLock_ReadOnly);f.serial=++mySerial;{std::lock_guard<std::mutex>l(myMutex);myFrame=std::move(f);myWarning.clear();}myFrames++;myLastW=w;myLastH=h;}
 void streamError(NSError*e){std::lock_guard<std::mutex>l(myMutex);myWarning=e.localizedDescription.UTF8String?:"Screen capture stopped";myRunning=false;}
private:
 static void addInt(OP_ParameterManager*m,const char*n,const char*l,int d,int lo,int hi){OP_NumericParameter p(n);p.label=l;p.page="Screen Capture";p.defaultValues[0]=d;p.minSliders[0]=lo;p.maxSliders[0]=hi;p.minValues[0]=lo;p.maxValues[0]=hi;p.clampMins[0]=p.clampMaxes[0]=true;m->appendInt(p);}
 void start(std::string mode,int index,int w,int h,int fps,bool cursor){myStarting=true;if(myStream){[myStream stopCaptureWithCompletionHandler:^(NSError*){}];myStream=nil;}__weak TDScreenCaptureOutput*weakOutput=myOutput;[SCShareableContent getShareableContentExcludingDesktopWindows:NO onScreenWindowsOnly:YES completionHandler:^(SCShareableContent*c,NSError*e){TDScreenCaptureOutput*output=weakOutput;if(!output||!output.owner)return;ScreenCaptureTOP*self=static_cast<ScreenCaptureTOP*>(output.owner);if(e||!c){self->streamError(e);self->myStarting=false;return;}self->mySources=mode=="window"?c.windows.count:c.displays.count;SCContentFilter*filter=nil;size_t nativeW=0,nativeH=0;if(mode=="window"){if(index>=(int)c.windows.count){self->setWarning("Window index is out of range");self->myStarting=false;return;}SCWindow*x=c.windows[index];filter=[[SCContentFilter alloc]initWithDesktopIndependentWindow:x];nativeW=x.frame.size.width;nativeH=x.frame.size.height;}else{if(index>=(int)c.displays.count){self->setWarning("Display index is out of range");self->myStarting=false;return;}SCDisplay*x=c.displays[index];filter=[[SCContentFilter alloc]initWithDisplay:x excludingWindows:@[]];nativeW=x.width;nativeH=x.height;}SCStreamConfiguration*cfg=[SCStreamConfiguration new];cfg.width=w>0?w:nativeW;cfg.height=h>0?h:nativeH;cfg.minimumFrameInterval=CMTimeMake(1,fps);cfg.pixelFormat=kCVPixelFormatType_32BGRA;cfg.showsCursor=cursor;cfg.queueDepth=3;self->myStream=[[SCStream alloc]initWithFilter:filter configuration:cfg delegate:output];NSError*add=nil;[self->myStream addStreamOutput:output type:SCStreamOutputTypeScreen sampleHandlerQueue:dispatch_get_global_queue(QOS_CLASS_USER_INTERACTIVE,0) error:&add];if(add){self->streamError(add);self->myStarting=false;return;}[self->myStream startCaptureWithCompletionHandler:^(NSError*startError){TDScreenCaptureOutput*current=weakOutput;if(!current||!current.owner)return;ScreenCaptureTOP*owner=static_cast<ScreenCaptureTOP*>(current.owner);owner->myStarting=false;if(startError)owner->streamError(startError);else owner->myRunning=true;}];}];}
 void setWarning(const char*s){std::lock_guard<std::mutex>l(myMutex);myWarning=s;}
 TOP_Context*myContext;TDScreenCaptureOutput*myOutput=nil;SCStream*myStream=nil;std::mutex myMutex;Frame myFrame;std::string myWarning,mySig;uint64_t mySerial=0,myUploaded=0;std::atomic<uint64_t>myExec{0},myFrames{0};std::atomic<int>mySources{0},myLastW{0},myLastH{0};std::atomic<bool>myStarting{false},myRunning{false};
};}
@implementation TDScreenCaptureOutput
-(void)stream:(SCStream*)stream didOutputSampleBuffer:(CMSampleBufferRef)sample ofType:(SCStreamOutputType)type{if(type==SCStreamOutputTypeScreen&&self.owner)static_cast<ScreenCaptureTOP*>(self.owner)->receive(sample);}
-(void)stream:(SCStream*)stream didStopWithError:(NSError*)error{if(self.owner)static_cast<ScreenCaptureTOP*>(self.owner)->streamError(error);}
@end
extern "C"{DLLEXPORT void FillTOPPluginInfo(TOP_PluginInfo*i){if(!i->setAPIVersion(TOPCPlusPlusAPIVersion))return;i->executeMode=TOP_ExecuteMode::CPUMem;i->customOPInfo.opType->setString("Screencapture");i->customOPInfo.opLabel->setString("Apple Screen Capture");i->customOPInfo.opIcon->setString("SCP");i->customOPInfo.authorName->setString("TDAppleML");i->customOPInfo.minInputs=0;i->customOPInfo.maxInputs=0;}DLLEXPORT TOP_CPlusPlusBase*CreateTOPInstance(const OP_NodeInfo*i,TOP_Context*c){return new ScreenCaptureTOP(i,c);}DLLEXPORT void DestroyTOPInstance(TOP_CPlusPlusBase*i,TOP_Context*){delete static_cast<ScreenCaptureTOP*>(i);}}
