#import <Foundation/Foundation.h>
#import <CoreImage/CoreImage.h>
#include <atomic>
#include <chrono>
#include <condition_variable>
#include <mutex>
#include <string>
#include <thread>
#include <vector>
#include "TOP_CPlusPlusBase.h"
#include "CPlusPlus_Common.h"
using namespace TD;
namespace {struct Result{std::vector<uint8_t>p;uint32_t w=0,h=0;uint64_t serial=0;};struct Settings{bool redEye=false,crop=false,level=true,flip=true;};class ImageAutoEnhanceTOP final:public TOP_CPlusPlusBase{
public:ImageAutoEnhanceTOP(const OP_NodeInfo*,TOP_Context*c):myContext(c){myThread=std::thread([this]{worker();});}~ImageAutoEnhanceTOP()override{{std::lock_guard<std::mutex>l(myMutex);myQuit=true;}myCond.notify_all();if(myThread.joinable())myThread.join();}void getGeneralInfo(TOP_GeneralInfo*g,const OP_Inputs*,void*)override{g->cookEveryFrameIfAsked=true;}
 void execute(TOP_Output*out,const OP_Inputs*in,void*)override{myExec++;bool active=in->getParInt("Active")!=0;Settings s;s.redEye=in->getParInt("Redeye");s.crop=in->getParInt("Crop");s.level=in->getParInt("Level");s.flip=in->getParInt("Flip");std::string sig=std::to_string(s.redEye)+std::to_string(s.crop)+std::to_string(s.level)+std::to_string(s.flip);if(sig!=mySig){mySig=sig;myLast=-1;}const OP_TOPInput*top=in->getInputTOP(0);if(active&&top&&(int64_t)top->totalCooks!=myLast){std::unique_lock<std::mutex>l(myMutex,std::try_to_lock);if(l.owns_lock()&&!myPending&&!myBusy){OP_TOPInputDownloadOptions o;o.pixelFormat=OP_PixelFormat::BGRA8Fixed;o.verticalFlip=s.flip;myDownload=top->downloadTexture(o,nullptr);if(myDownload){mySettings=s;myPending=true;myLast=top->totalCooks;mySubmit++;l.unlock();myCond.notify_one();}}}Result r;{std::lock_guard<std::mutex>l(myMutex);if(myResult.serial==myUploaded||myResult.p.empty())return;r=myResult;myUploaded=r.serial;}TOP_UploadInfo ui;ui.textureDesc.texDim=OP_TexDim::e2D;ui.textureDesc.width=r.w;ui.textureDesc.height=r.h;ui.textureDesc.pixelFormat=OP_PixelFormat::BGRA8Fixed;auto b=myContext->createOutputBuffer(r.p.size(),TOP_BufferFlags::None,nullptr);if(!b)return;memcpy(b->data,r.p.data(),r.p.size());out->uploadBuffer(&b,ui,nullptr);}
 void setupParameters(OP_ParameterManager*m,void*)override{addToggle(m,"Active","Active",1);addToggle(m,"Redeye","Red Eye Correction",0);addToggle(m,"Crop","Auto Crop",0);addToggle(m,"Level","Auto Level",1);addToggle(m,"Flip","Flip Image Vertically",1);}
 int32_t getNumInfoCHOPChans(void*)override{return 6;}void getInfoCHOPChan(int32_t i,OP_InfoCHOPChan*c,void*)override{const char*n[]={"executes","submits","processes","process_ms","filters","valid"};float v[]={(float)myExec.load(),(float)mySubmit.load(),(float)myProcess.load(),myMs.load(),(float)myFilters.load(),myValid?1.f:0.f};c->name->setString(n[i]);c->value=v[i];}bool getInfoDATSize(OP_InfoDATSize*i,void*)override{i->rows=1;i->cols=2;i->byColumn=false;return true;}void getInfoDATEntries(int32_t,int32_t,OP_InfoDATEntries*e,void*)override{e->values[0]->setString("filters");std::lock_guard<std::mutex>l(myMutex);e->values[1]->setString(myFilterNames.c_str());}void getWarningString(OP_String*s,void*)override{std::lock_guard<std::mutex>l(myMutex);if(!myWarning.empty())s->setString(myWarning.c_str());}
private:static void addToggle(OP_ParameterManager*m,const char*n,const char*l,int d){OP_NumericParameter p(n);p.label=l;p.page="Image Auto Enhance";p.defaultValues[0]=d;m->appendToggle(p);}void worker(){while(true){OP_SmartRef<OP_TOPDownloadResult>d;Settings s;{std::unique_lock<std::mutex>l(myMutex);myCond.wait(l,[this]{return myQuit||myPending;});if(myQuit)return;d=std::move(myDownload);s=mySettings;myPending=false;myBusy=true;}Result r;std::string w,n;int count=0;auto t=std::chrono::steady_clock::now();bool ok=process(d,s,r,w,n,count);myMs=std::chrono::duration<float,std::milli>(std::chrono::steady_clock::now()-t).count();myProcess++;myFilters=count;myValid=ok;{std::lock_guard<std::mutex>l(myMutex);if(ok){r.serial=++mySerial;myResult=std::move(r);}myWarning=std::move(w);myFilterNames=std::move(n);myBusy=false;}}}
 static bool process(OP_SmartRef<OP_TOPDownloadResult>&d,const Settings&s,Result&r,std::string&w,std::string&names,int&count){void*p=d?d->getData():nullptr;uint32_t iw=d?d->textureDesc.width:0,ih=d?d->textureDesc.height:0;if(!p||!iw||!ih)return false;@autoreleasepool{@synchronized([CIFilter class]){CGColorSpaceRef cs=CGColorSpaceCreateDeviceRGB();NSData*data=[NSData dataWithBytes:p length:(size_t)iw*ih*4];CIImage*image=[CIImage imageWithBitmapData:data bytesPerRow:iw*4 size:CGSizeMake(iw,ih) format:kCIFormatBGRA8 colorSpace:cs];NSDictionary*opts=@{kCIImageAutoAdjustRedEye:@(s.redEye),kCIImageAutoAdjustCrop:@(s.crop),kCIImageAutoAdjustLevel:@(s.level)};NSArray<CIFilter*>*filters=[image autoAdjustmentFiltersWithOptions:opts];CIImage*out=image;for(CIFilter*f in filters){[f setValue:out forKey:kCIInputImageKey];if(f.outputImage)out=f.outputImage;if(!names.empty())names+=",";names+=f.name.UTF8String?:"unknown";}count=filters.count;CGRect e=out.extent;if(CGRectIsInfinite(e)||CGRectIsEmpty(e))e=CGRectMake(0,0,iw,ih);r.w=std::max(1,(int)ceil(e.size.width));r.h=std::max(1,(int)ceil(e.size.height));out=[out imageByApplyingTransform:CGAffineTransformMakeTranslation(-e.origin.x,-e.origin.y)];r.p.resize((size_t)r.w*r.h*4);[[CIContext contextWithOptions:@{kCIContextUseSoftwareRenderer:@NO}] render:out toBitmap:r.p.data() rowBytes:r.w*4 bounds:CGRectMake(0,0,r.w,r.h) format:kCIFormatBGRA8 colorSpace:cs];std::vector<uint8_t>row((size_t)r.w*4);for(uint32_t y=0;y<r.h/2;y++){uint8_t*a=r.p.data()+(size_t)y*r.w*4,*b=r.p.data()+(size_t)(r.h-1-y)*r.w*4;memcpy(row.data(),a,row.size());memcpy(a,b,row.size());memcpy(b,row.data(),row.size());}CGColorSpaceRelease(cs);return true;}}}
 TOP_Context*myContext;std::thread myThread;std::condition_variable myCond;std::mutex myMutex;bool myQuit=false,myPending=false,myBusy=false;OP_SmartRef<OP_TOPDownloadResult>myDownload;Settings mySettings;Result myResult;std::string mySig,myWarning,myFilterNames;int64_t myLast=-1;uint64_t mySerial=0,myUploaded=0;std::atomic<uint64_t>myExec{0},mySubmit{0},myProcess{0};std::atomic<int>myFilters{0};std::atomic<float>myMs{0};std::atomic<bool>myValid{false};};}
extern "C"{DLLEXPORT void FillTOPPluginInfo(TOP_PluginInfo*i){if(!i->setAPIVersion(TOPCPlusPlusAPIVersion))return;i->executeMode=TOP_ExecuteMode::CPUMem;i->customOPInfo.opType->setString("Coreimageenhance");i->customOPInfo.opLabel->setString("CI Enhance");i->customOPInfo.opIcon->setString("CIE");i->customOPInfo.authorName->setString("TDAppleML");i->customOPInfo.minInputs=1;i->customOPInfo.maxInputs=1;}DLLEXPORT TOP_CPlusPlusBase*CreateTOPInstance(const OP_NodeInfo*i,TOP_Context*c){return new ImageAutoEnhanceTOP(i,c);}DLLEXPORT void DestroyTOPInstance(TOP_CPlusPlusBase*i,TOP_Context*){delete static_cast<ImageAutoEnhanceTOP*>(i);}}
