#import <Foundation/Foundation.h>
#import <CoreVideo/CoreVideo.h>
#import <Vision/Vision.h>
#include <atomic>
#include <chrono>
#include <condition_variable>
#include <mutex>
#include <string>
#include <thread>
#include "CHOP_CPlusPlusBase.h"
#include "CPlusPlus_Common.h"
using namespace TD;
namespace {struct Result{float v[8]={};};class VisionHorizonCHOP final:public CHOP_CPlusPlusBase{
public:VisionHorizonCHOP(const OP_NodeInfo*){myThread=std::thread([this]{worker();});}~VisionHorizonCHOP()override{{std::lock_guard<std::mutex>l(myMutex);myQuit=true;}myCond.notify_all();if(myThread.joinable())myThread.join();}void getGeneralInfo(CHOP_GeneralInfo*g,const OP_Inputs*,void*)override{g->cookEveryFrameIfAsked=true;g->timeslice=false;}bool getOutputInfo(CHOP_OutputInfo*i,const OP_Inputs*,void*)override{i->numChannels=8;i->numSamples=1;i->startIndex=0;return true;}void getChannelName(int32_t i,OP_String*n,const OP_Inputs*,void*)override{const char*x[]={"valid","angle","angledeg","transform/a","transform/b","transform/c","transform/d","confidence"};n->setString(x[i]);}
 void execute(CHOP_Output*out,const OP_Inputs*in,void*)override{myExec++;bool active=in->getParInt("Active")!=0,flip=in->getParInt("Flip")!=0;const OP_TOPInput*top=in->getParTOP("Top");if(active&&top&&(int64_t)top->totalCooks!=myLast){std::unique_lock<std::mutex>l(myMutex,std::try_to_lock);if(l.owns_lock()&&!myPending&&!myBusy){OP_TOPInputDownloadOptions o;o.pixelFormat=OP_PixelFormat::BGRA8Fixed;o.verticalFlip=flip;myDownload=top->downloadTexture(o,nullptr);if(myDownload){myPending=true;myLast=top->totalCooks;mySubmit++;l.unlock();myCond.notify_one();}}}Result r;{std::lock_guard<std::mutex>l(myMutex);r=myResult;}for(int i=0;i<8;i++)out->channels[i][0]=active?r.v[i]:0;}
 void setupParameters(OP_ParameterManager*m,void*)override{OP_StringParameter t("Top");t.label="TOP";t.page="Vision Horizon";m->appendTOP(t);OP_NumericParameter a("Active");a.label="Active";a.page="Vision Horizon";a.defaultValues[0]=1;m->appendToggle(a);OP_NumericParameter f("Flip");f.label="Flip Image Vertically";f.page="Vision Horizon";f.defaultValues[0]=1;m->appendToggle(f);}
 int32_t getNumInfoCHOPChans(void*)override{return 5;}void getInfoCHOPChan(int32_t i,OP_InfoCHOPChan*c,void*)override{const char*n[]={"executes","submits","analyzes","analyze_ms","valid"};float v[]={(float)myExec.load(),(float)mySubmit.load(),(float)myAnalyze.load(),myMs.load(),myValid?1.f:0.f};c->name->setString(n[i]);c->value=v[i];}void getWarningString(OP_String*s,void*)override{std::lock_guard<std::mutex>l(myMutex);if(!myWarning.empty())s->setString(myWarning.c_str());}
private:void worker(){while(true){OP_SmartRef<OP_TOPDownloadResult>d;{std::unique_lock<std::mutex>l(myMutex);myCond.wait(l,[this]{return myQuit||myPending;});if(myQuit)return;d=std::move(myDownload);myPending=false;myBusy=true;}Result r;std::string w;auto t=std::chrono::steady_clock::now();bool ok=analyze(d,r,w);myMs=std::chrono::duration<float,std::milli>(std::chrono::steady_clock::now()-t).count();myAnalyze++;myValid=ok;{std::lock_guard<std::mutex>l(myMutex);myResult=r;myWarning=std::move(w);myBusy=false;}}}
 static bool analyze(OP_SmartRef<OP_TOPDownloadResult>&d,Result&r,std::string&w){void*data=d?d->getData():nullptr;uint32_t iw=d?d->textureDesc.width:0,ih=d?d->textureDesc.height:0;if(!data||!iw||!ih)return false;@autoreleasepool{CVPixelBufferRef p=nullptr;CVPixelBufferCreateWithBytes(nullptr,iw,ih,kCVPixelFormatType_32BGRA,data,(size_t)iw*4,nullptr,nullptr,nullptr,&p);if(!p)return false;VNDetectHorizonRequest*q=[VNDetectHorizonRequest new];VNImageRequestHandler*h=[[VNImageRequestHandler alloc]initWithCVPixelBuffer:p options:@{}];NSError*e=nil;bool ok=[h performRequests:@[q] error:&e]&&q.results.count;VNHorizonObservation*o=ok?q.results.firstObject:nil;if(o){CGAffineTransform t=o.transform;r.v[0]=1;r.v[1]=o.angle;r.v[2]=o.angle*180/M_PI;r.v[3]=t.a;r.v[4]=t.b;r.v[5]=t.c;r.v[6]=t.d;r.v[7]=o.confidence;}else if(e)w=e.localizedDescription.UTF8String?:"Horizon detection failed";CVPixelBufferRelease(p);return ok;}}
 std::thread myThread;std::condition_variable myCond;std::mutex myMutex;bool myQuit=false,myPending=false,myBusy=false;OP_SmartRef<OP_TOPDownloadResult>myDownload;Result myResult;std::string myWarning;int64_t myLast=-1;std::atomic<uint64_t>myExec{0},mySubmit{0},myAnalyze{0};std::atomic<float>myMs{0};std::atomic<bool>myValid{false};};}
extern "C"{DLLEXPORT void FillCHOPPluginInfo(CHOP_PluginInfo*i){if(!i->setAPIVersion(CHOPCPlusPlusAPIVersion))return;i->customOPInfo.opType->setString("Visionhorizon");i->customOPInfo.opLabel->setString("Vision Horizon");i->customOPInfo.opIcon->setString("VHZ");i->customOPInfo.authorName->setString("SYGNAL Inc.");i->customOPInfo.minInputs=0;i->customOPInfo.maxInputs=0;}DLLEXPORT CHOP_CPlusPlusBase*CreateCHOPInstance(const OP_NodeInfo*i){return new VisionHorizonCHOP(i);}DLLEXPORT void DestroyCHOPInstance(CHOP_CPlusPlusBase*i){delete static_cast<VisionHorizonCHOP*>(i);}}
