#import <Foundation/Foundation.h>
#import <ScreenCaptureKit/ScreenCaptureKit.h>
#import <CoreMedia/CoreMedia.h>
#import <AudioToolbox/AudioToolbox.h>
#include <algorithm>
#include <atomic>
#include <mutex>
#include <string>
#include <vector>
#include "CHOP_CPlusPlusBase.h"
#include "CPlusPlus_Common.h"
using namespace TD;
namespace { class SystemAudioCHOP; }
@interface TDSystemAudioOutput:NSObject<SCStreamOutput,SCStreamDelegate>@property(nonatomic,assign)void*owner;@end
namespace {
class SystemAudioCHOP final:public CHOP_CPlusPlusBase{
public:SystemAudioCHOP(const OP_NodeInfo*){myOutput=[TDSystemAudioOutput new];myOutput.owner=this;}~SystemAudioCHOP()override{myOutput.owner=nullptr;if(myStream)[myStream stopCaptureWithCompletionHandler:^(NSError*){}];myStream=nil;myOutput=nil;}
 void getGeneralInfo(CHOP_GeneralInfo*g,const OP_Inputs*,void*)override{g->cookEveryFrameIfAsked=true;g->timeslice=false;}
 bool getOutputInfo(CHOP_OutputInfo*i,const OP_Inputs*in,void*)override{myBlock=std::clamp(in->getParInt("Blocksamples"),64,8192);i->numChannels=2;i->numSamples=myBlock;i->startIndex=0;i->sampleRate=myRate.load();return true;}
 void getChannelName(int32_t i,OP_String*n,const OP_Inputs*,void*)override{n->setString(i?"right":"left");}
 void execute(CHOP_Output*out,const OP_Inputs*in,void*)override{myExec++;bool active=in->getParInt("Active")!=0;int index=std::max(0,in->getParInt("Display"));bool exclude=in->getParInt("Excludeapp")!=0;std::string sig=std::to_string(index)+(exclude?":1":":0");if(active&&sig!=mySig&&!myStarting){mySig=sig;start(index,exclude);}if(!active&&myStream){[myStream stopCaptureWithCompletionHandler:^(NSError*){}];myStream=nil;myRunning=false;}std::vector<float>l,r;{std::lock_guard<std::mutex>x(myMutex);l=myL;r=myR;}for(int s=0;s<myBlock;s++){int src=(int)l.size()-myBlock+s;out->channels[0][s]=active&&src>=0?l[src]:0;out->channels[1][s]=active&&src>=0&&src<(int)r.size()?r[src]:0;}}
 void setupParameters(OP_ParameterManager*m,void*)override{OP_NumericParameter a("Active");a.label="Active";a.page="System Audio";a.defaultValues[0]=1;m->appendToggle(a);addInt(m,"Display","Display Index",0,0,32);addInt(m,"Blocksamples","Block Samples",1024,64,8192);OP_NumericParameter e("Excludeapp");e.label="Exclude Current App Audio";e.page="System Audio";e.defaultValues[0]=1;m->appendToggle(e);OP_NumericParameter r("Restart");r.label="Restart Capture";r.page="System Audio";m->appendPulse(r);}
 void pulsePressed(const char*n,void*)override{if(!strcmp(n,"Restart")){mySig.clear();if(myStream){[myStream stopCaptureWithCompletionHandler:^(NSError*){}];myStream=nil;}myRunning=false;}}
 int32_t getNumInfoCHOPChans(void*)override{return 6;}void getInfoCHOPChan(int32_t i,OP_InfoCHOPChan*c,void*)override{const char*n[]={"executes","buffers","running","sources","sample_rate","channels"};float v[]={(float)myExec.load(),(float)myBuffers.load(),myRunning?1.f:0.f,(float)mySources.load(),myRate.load(),2};c->name->setString(n[i]);c->value=v[i];}void getWarningString(OP_String*s,void*)override{std::lock_guard<std::mutex>x(myMutex);if(!myWarning.empty())s->setString(myWarning.c_str());}
 void receive(CMSampleBufferRef sample){CMFormatDescriptionRef fd=CMSampleBufferGetFormatDescription(sample);const AudioStreamBasicDescription*asbd=fd?CMAudioFormatDescriptionGetStreamBasicDescription(fd):nullptr;CMBlockBufferRef block=CMSampleBufferGetDataBuffer(sample);if(!asbd||!block)return;AudioBufferList list;CMBlockBufferRef retained=nullptr;OSStatus err=CMSampleBufferGetAudioBufferListWithRetainedBlockBuffer(sample,nullptr,&list,sizeof(list),nullptr,nullptr,kCMSampleBufferFlag_AudioBufferList_Assure16ByteAlignment,&retained);if(err)return;size_t frames=CMSampleBufferGetNumSamples(sample);std::vector<float>l(frames),r(frames);if((asbd->mFormatFlags&kAudioFormatFlagIsFloat)&&asbd->mBitsPerChannel==32){if(list.mNumberBuffers>=2){memcpy(l.data(),list.mBuffers[0].mData,std::min(l.size()*4,(size_t)list.mBuffers[0].mDataByteSize));memcpy(r.data(),list.mBuffers[1].mData,std::min(r.size()*4,(size_t)list.mBuffers[1].mDataByteSize));}else if(list.mNumberBuffers){float*p=(float*)list.mBuffers[0].mData;int ch=std::max(1,(int)asbd->mChannelsPerFrame);for(size_t i=0;i<frames;i++){l[i]=p[i*ch];r[i]=p[i*ch+std::min(1,ch-1)];}}}if(retained)CFRelease(retained);{std::lock_guard<std::mutex>x(myMutex);myL=std::move(l);myR=std::move(r);myWarning.clear();}myRate=asbd->mSampleRate;myBuffers++;}
 void failed(NSError*e){std::lock_guard<std::mutex>x(myMutex);myWarning=e.localizedDescription.UTF8String?:"System audio capture stopped";myRunning=false;}
private:static void addInt(OP_ParameterManager*m,const char*n,const char*l,int d,int lo,int hi){OP_NumericParameter p(n);p.label=l;p.page="System Audio";p.defaultValues[0]=d;p.minSliders[0]=lo;p.maxSliders[0]=hi;p.minValues[0]=lo;p.maxValues[0]=hi;p.clampMins[0]=p.clampMaxes[0]=true;m->appendInt(p);}
 void start(int index,bool exclude){myStarting=true;if(myStream){[myStream stopCaptureWithCompletionHandler:^(NSError*){}];myStream=nil;}__weak TDSystemAudioOutput*weak=myOutput;[SCShareableContent getShareableContentExcludingDesktopWindows:NO onScreenWindowsOnly:NO completionHandler:^(SCShareableContent*c,NSError*e){TDSystemAudioOutput*o=weak;if(!o||!o.owner)return;auto*self=static_cast<SystemAudioCHOP*>(o.owner);if(e||!c){self->failed(e);self->myStarting=false;return;}self->mySources=c.displays.count;if(index>=(int)c.displays.count){self->failed([NSError errorWithDomain:@"TDAppleML" code:1 userInfo:@{NSLocalizedDescriptionKey:@"Display index is out of range"}]);self->myStarting=false;return;}SCContentFilter*f=[[SCContentFilter alloc]initWithDisplay:c.displays[index] excludingWindows:@[]];SCStreamConfiguration*cfg=[SCStreamConfiguration new];cfg.capturesAudio=YES;cfg.excludesCurrentProcessAudio=exclude;cfg.sampleRate=48000;cfg.channelCount=2;cfg.width=2;cfg.height=2;cfg.minimumFrameInterval=CMTimeMake(1,10);self->myStream=[[SCStream alloc]initWithFilter:f configuration:cfg delegate:o];NSError*add=nil;[self->myStream addStreamOutput:o type:SCStreamOutputTypeAudio sampleHandlerQueue:dispatch_get_global_queue(QOS_CLASS_USER_INTERACTIVE,0) error:&add];if(add){self->failed(add);self->myStarting=false;return;}[self->myStream startCaptureWithCompletionHandler:^(NSError*x){TDSystemAudioOutput*q=weak;if(!q||!q.owner)return;auto*owner=static_cast<SystemAudioCHOP*>(q.owner);owner->myStarting=false;if(x)owner->failed(x);else owner->myRunning=true;}];}];}
 TDSystemAudioOutput*myOutput=nil;SCStream*myStream=nil;std::mutex myMutex;std::vector<float>myL,myR;std::string myWarning,mySig;int myBlock=1024;std::atomic<uint64_t>myExec{0},myBuffers{0};std::atomic<int>mySources{0};std::atomic<float>myRate{48000};std::atomic<bool>myStarting{false},myRunning{false};};}
@implementation TDSystemAudioOutput
-(void)stream:(SCStream*)s didOutputSampleBuffer:(CMSampleBufferRef)b ofType:(SCStreamOutputType)t{if(t==SCStreamOutputTypeAudio&&self.owner)static_cast<SystemAudioCHOP*>(self.owner)->receive(b);}-(void)stream:(SCStream*)s didStopWithError:(NSError*)e{if(self.owner)static_cast<SystemAudioCHOP*>(self.owner)->failed(e);}
@end
extern "C"{DLLEXPORT void FillCHOPPluginInfo(CHOP_PluginInfo*i){if(!i->setAPIVersion(CHOPCPlusPlusAPIVersion))return;i->customOPInfo.opType->setString("Systemaudio");i->customOPInfo.opLabel->setString("System Audio");i->customOPInfo.opIcon->setString("SAU");i->customOPInfo.authorName->setString("TDAppleML");i->customOPInfo.minInputs=0;i->customOPInfo.maxInputs=0;}DLLEXPORT CHOP_CPlusPlusBase*CreateCHOPInstance(const OP_NodeInfo*i){return new SystemAudioCHOP(i);}DLLEXPORT void DestroyCHOPInstance(CHOP_CPlusPlusBase*i){delete static_cast<SystemAudioCHOP*>(i);}}
