// VisionKeystone TOP — VisionRect CHOPまたは手動四隅による透視補正。
#import <Foundation/Foundation.h>
#import <CoreImage/CoreImage.h>
#include <algorithm>
#include <atomic>
#include <chrono>
#include <condition_variable>
#include <cstring>
#include <mutex>
#include <string>
#include <thread>
#include <vector>
#include "TOP_CPlusPlusBase.h"
#include "CPlusPlus_Common.h"
using namespace TD;
namespace {
struct Settings { float p[8]={0,1,1,1,1,0,0,0}; int outW=0,outH=0; bool flip=true; };
struct Result { std::vector<uint8_t> pixels; uint32_t w=0,h=0; uint64_t serial=0; };
class VisionKeystoneTOP final:public TOP_CPlusPlusBase{
public:
 VisionKeystoneTOP(const OP_NodeInfo*,TOP_Context*c):myContext(c){myThread=std::thread([this]{worker();});}
 ~VisionKeystoneTOP()override{{std::lock_guard<std::mutex>l(myMutex);myQuit=true;}myCond.notify_all();if(myThread.joinable())myThread.join();}
 void getGeneralInfo(TOP_GeneralInfo*g,const OP_Inputs*,void*)override{g->cookEveryFrameIfAsked=true;}
 void execute(TOP_Output*out,const OP_Inputs*in,void*)override{
  myExec++;bool active=in->getParInt("Active")!=0;Settings s;s.flip=in->getParInt("Flip")!=0;s.outW=std::max(0,in->getParInt("Outputwidth"));s.outH=std::max(0,in->getParInt("Outputheight"));
  s.p[0]=in->getParDouble("Topleft",0);s.p[1]=in->getParDouble("Topleft",1);s.p[2]=in->getParDouble("Topright",0);s.p[3]=in->getParDouble("Topright",1);s.p[4]=in->getParDouble("Bottomright",0);s.p[5]=in->getParDouble("Bottomright",1);s.p[6]=in->getParDouble("Bottomleft",0);s.p[7]=in->getParDouble("Bottomleft",1);
  if(in->getParInt("Usechop")){const OP_CHOPInput*c=in->getParCHOP("Cornerchop");int slot=std::clamp(in->getParInt("Slot"),1,100);if(c){const char*fields[]={"tl:u","tl:v","tr:u","tr:v","br:u","br:v","bl:u","bl:v"};for(int k=0;k<8;k++){std::string want="rect"+std::to_string(slot)+"/"+fields[k];for(int i=0;i<c->numChannels;i++)if(want==c->getChannelName(i)&&c->numSamples){s.p[k]=c->getChannelData(i)[0];break;}}}}
  std::string sig=std::to_string(s.outW)+":"+std::to_string(s.outH)+(s.flip?":1":":0");for(float v:s.p)sig+=":"+std::to_string(v);if(sig!=mySig){mySig=sig;myLast=-1;}const OP_TOPInput*top=in->getInputTOP(0);if(active&&top&&(int64_t)top->totalCooks!=myLast){std::unique_lock<std::mutex>l(myMutex,std::try_to_lock);if(l.owns_lock()&&!myPending&&!myBusy){OP_TOPInputDownloadOptions o;o.pixelFormat=OP_PixelFormat::BGRA8Fixed;o.verticalFlip=s.flip;myDownload=top->downloadTexture(o,nullptr);if(myDownload){mySettings=s;myPending=true;myLast=top->totalCooks;mySubmit++;l.unlock();myCond.notify_one();}}}
  Result r;{std::lock_guard<std::mutex>l(myMutex);if(myResult.serial==myUploaded||myResult.pixels.empty())return;r=myResult;myUploaded=r.serial;}TOP_UploadInfo ui;ui.textureDesc.texDim=OP_TexDim::e2D;ui.textureDesc.width=r.w;ui.textureDesc.height=r.h;ui.textureDesc.pixelFormat=OP_PixelFormat::BGRA8Fixed;auto b=myContext->createOutputBuffer(r.pixels.size(),TOP_BufferFlags::None,nullptr);if(!b)return;memcpy(b->data,r.pixels.data(),r.pixels.size());out->uploadBuffer(&b,ui,nullptr);
 }
 void setupParameters(OP_ParameterManager*m,void*)override{addToggle(m,"Active","Active",1);addToggle(m,"Usechop","Use VisionRect CHOP",1);OP_StringParameter c("Cornerchop");c.label="Corner CHOP";c.page="Vision Keystone";m->appendCHOP(c);OP_NumericParameter slot("Slot");slot.label="Rectangle Slot";slot.page="Vision Keystone";slot.defaultValues[0]=1;slot.minSliders[0]=1;slot.maxSliders[0]=10;slot.minValues[0]=1;slot.maxValues[0]=100;slot.clampMins[0]=slot.clampMaxes[0]=true;m->appendInt(slot);addXY(m,"Topleft","Top Left",0,1);addXY(m,"Topright","Top Right",1,1);addXY(m,"Bottomright","Bottom Right",1,0);addXY(m,"Bottomleft","Bottom Left",0,0);addInt(m,"Outputwidth","Output Width (0=Auto)",0,0,4096);addInt(m,"Outputheight","Output Height (0=Auto)",0,0,4096);addToggle(m,"Flip","Flip Image Vertically",1);}
 int32_t getNumInfoCHOPChans(void*)override{return 5;}void getInfoCHOPChan(int32_t i,OP_InfoCHOPChan*c,void*)override{const char*n[]={"executes","submits","processes","process_ms","valid"};float v[]={(float)myExec.load(),(float)mySubmit.load(),(float)myProcess.load(),myMs.load(),myValid.load()?1.f:0.f};c->name->setString(n[i]);c->value=v[i];}void getWarningString(OP_String*s,void*)override{std::lock_guard<std::mutex>l(myMutex);if(!myWarning.empty())s->setString(myWarning.c_str());}
private:
 static void addToggle(OP_ParameterManager*m,const char*n,const char*l,int d){OP_NumericParameter p(n);p.label=l;p.page="Vision Keystone";p.defaultValues[0]=d;m->appendToggle(p);}static void addInt(OP_ParameterManager*m,const char*n,const char*l,int d,int lo,int hi){OP_NumericParameter p(n);p.label=l;p.page="Vision Keystone";p.defaultValues[0]=d;p.minSliders[0]=lo;p.maxSliders[0]=hi;p.minValues[0]=lo;p.maxValues[0]=hi;p.clampMins[0]=p.clampMaxes[0]=true;m->appendInt(p);}static void addXY(OP_ParameterManager*m,const char*n,const char*l,double x,double y){OP_NumericParameter p(n);p.label=l;p.page="Vision Keystone";p.defaultValues[0]=x;p.defaultValues[1]=y;for(int i=0;i<2;i++){p.minSliders[i]=0;p.maxSliders[i]=1;p.minValues[i]=0;p.maxValues[i]=1;p.clampMins[i]=p.clampMaxes[i]=true;}m->appendXY(p);}
 void worker(){while(true){OP_SmartRef<OP_TOPDownloadResult>d;Settings s;{std::unique_lock<std::mutex>l(myMutex);myCond.wait(l,[this]{return myQuit||myPending;});if(myQuit)return;d=std::move(myDownload);s=mySettings;myPending=false;myBusy=true;}Result r;std::string warning;auto t=std::chrono::steady_clock::now();bool ok=process(d,s,r,warning);myMs=std::chrono::duration<float,std::milli>(std::chrono::steady_clock::now()-t).count();myProcess++;myValid=ok;{std::lock_guard<std::mutex>l(myMutex);if(ok){r.serial=++mySerial;myResult=std::move(r);}myWarning=std::move(warning);myBusy=false;}}}
 static bool process(OP_SmartRef<OP_TOPDownloadResult>&d,const Settings&s,Result&r,std::string&w){if(!d)return false;uint32_t iw=d->textureDesc.width,ih=d->textureDesc.height;void*data=d->getData();if(!data||!iw||!ih)return false;@autoreleasepool{@synchronized([CIFilter class]){CGColorSpaceRef cs=CGColorSpaceCreateDeviceRGB();NSData*bytes=[NSData dataWithBytes:data length:(size_t)iw*ih*4];CIImage*image=[CIImage imageWithBitmapData:bytes bytesPerRow:iw*4 size:CGSizeMake(iw,ih) format:kCIFormatBGRA8 colorSpace:cs];CIFilter*f=[CIFilter filterWithName:@"CIPerspectiveCorrection"];[f setValue:image forKey:kCIInputImageKey];NSArray*keys=@[@"inputTopLeft",@"inputTopRight",@"inputBottomRight",@"inputBottomLeft"];for(int i=0;i<4;i++)[f setValue:[CIVector vectorWithX:s.p[i*2]*iw Y:s.p[i*2+1]*ih] forKey:keys[i]];CIImage*o=f.outputImage;if(!o){CGColorSpaceRelease(cs);w="Perspective correction produced no image";return false;}CGRect e=o.extent;uint32_t ow=s.outW>0?s.outW:(uint32_t)std::max(1.0,round(e.size.width));uint32_t oh=s.outH>0?s.outH:(uint32_t)std::max(1.0,round(e.size.height));CGAffineTransform tr=CGAffineTransformMakeTranslation(-e.origin.x,-e.origin.y);o=[o imageByApplyingTransform:tr];if(ow!=(uint32_t)round(e.size.width)||oh!=(uint32_t)round(e.size.height)){CGFloat sx=ow/std::max(1.0,e.size.width),sy=oh/std::max(1.0,e.size.height);o=[o imageByApplyingTransform:CGAffineTransformMakeScale(sx,sy)];}r.w=ow;r.h=oh;r.pixels.resize((size_t)ow*oh*4);CIContext*ctx=[CIContext contextWithOptions:@{kCIContextUseSoftwareRenderer:@NO}];[ctx render:o toBitmap:r.pixels.data() rowBytes:ow*4 bounds:CGRectMake(0,0,ow,oh) format:kCIFormatBGRA8 colorSpace:cs];std::vector<uint8_t>row((size_t)ow*4);for(uint32_t y=0;y<oh/2;y++){uint8_t*a=r.pixels.data()+(size_t)y*ow*4;uint8_t*b=r.pixels.data()+(size_t)(oh-1-y)*ow*4;memcpy(row.data(),a,row.size());memcpy(a,b,row.size());memcpy(b,row.data(),row.size());}CGColorSpaceRelease(cs);return true;}}}
 TOP_Context*myContext;std::thread myThread;std::condition_variable myCond;std::mutex myMutex;bool myQuit=false,myPending=false,myBusy=false;OP_SmartRef<OP_TOPDownloadResult>myDownload;Settings mySettings;Result myResult;std::string myWarning,mySig;int64_t myLast=-1;uint64_t mySerial=0,myUploaded=0;std::atomic<uint64_t>myExec{0},mySubmit{0},myProcess{0};std::atomic<float>myMs{0};std::atomic<bool>myValid{false};
};}
extern "C"{DLLEXPORT void FillTOPPluginInfo(TOP_PluginInfo*i){if(!i->setAPIVersion(TOPCPlusPlusAPIVersion))return;i->executeMode=TOP_ExecuteMode::CPUMem;i->customOPInfo.opType->setString("Visionkeystone");i->customOPInfo.opLabel->setString("CoreImage Keystone");i->customOPInfo.opIcon->setString("VKS");i->customOPInfo.authorName->setString("TDAppleML");i->customOPInfo.minInputs=1;i->customOPInfo.maxInputs=1;}DLLEXPORT TOP_CPlusPlusBase*CreateTOPInstance(const OP_NodeInfo*i,TOP_Context*c){return new VisionKeystoneTOP(i,c);}DLLEXPORT void DestroyTOPInstance(TOP_CPlusPlusBase*i,TOP_Context*){delete static_cast<VisionKeystoneTOP*>(i);}}
