// CoreML CHOP — generic image-input Core ML inference with flattened vector output.
#import <Foundation/Foundation.h>
#import <CoreVideo/CoreVideo.h>
#import <CoreML/CoreML.h>
#import <Vision/Vision.h>
#include <algorithm>
#include <atomic>
#include <chrono>
#include <condition_variable>
#include <mutex>
#include <string>
#include <thread>
#include <vector>
#include "CHOP_CPlusPlusBase.h"
#include "CPlusPlus_Common.h"
using namespace TD;
namespace {
static std::string str(NSString*s){return s?s.UTF8String:"";}
struct Result{std::vector<float>values;std::string feature,shape;int total=0;};
struct State{std::string status="no model",error,input,outputs;};
class CoreMLCHOP final:public CHOP_CPlusPlusBase{
public:
 CoreMLCHOP(const OP_NodeInfo*){myThread=std::thread([this]{worker();});}
 ~CoreMLCHOP()override{{std::lock_guard<std::mutex>l(myMutex);myQuit=true;}myCond.notify_all();if(myThread.joinable())myThread.join();}
 void getGeneralInfo(CHOP_GeneralInfo*g,const OP_Inputs*,void*)override{g->cookEveryFrameIfAsked=true;g->timeslice=false;}
 bool getOutputInfo(CHOP_OutputInfo*i,const OP_Inputs*in,void*)override{myMaxValues=std::clamp(in->getParInt("Maxvalues"),1,65536);i->numChannels=2+myMaxValues;i->numSamples=1;i->startIndex=0;return true;}
 void getChannelName(int32_t i,OP_String*n,const OP_Inputs*,void*)override{if(i==0)n->setString("valid");else if(i==1)n->setString("count");else{char b[32];snprintf(b,sizeof(b),"value%d",i-2);n->setString(b);}}
 void execute(CHOP_Output*out,const OP_Inputs*in,void*)override{myExec++;bool active=in->getParInt("Active")!=0,flip=in->getParInt("Flip")!=0;const char*sc=in->getParString("Scaling");int scale=!strcmp(sc,"centercrop")?1:!strcmp(sc,"scalefit")?2:0;const char*cu=in->getParString("Computeunits");int units=!strcmp(cu,"cpugpu")?1:!strcmp(cu,"cpuonly")?2:!strcmp(cu,"cpuane")?3:0;std::string path=in->getParString("Modelfile")?:"",outputName=in->getParString("Outputname")?:"";
  {std::lock_guard<std::mutex>l(myMutex);if((path!=myRequestedPath||units!=myRequestedUnits||myForceReload)&&!path.empty()){myRequestedPath=path;myRequestedUnits=units;myForceReload=false;myNeedLoad=true;myCond.notify_one();}else if(path.empty()&&myState.status!="no model"){myState=State();myLoaded=false;}}
  std::string sig=outputName+":"+std::to_string(scale)+(flip?":1":":0");if(sig!=mySig){mySig=sig;myLast=-1;}
  const OP_TOPInput*top=in->getParTOP("Top");if(active&&top&&(int64_t)top->totalCooks!=myLast){std::unique_lock<std::mutex>l(myMutex,std::try_to_lock);if(l.owns_lock()&&!myPending&&!myBusy&&myLoaded){OP_TOPInputDownloadOptions o;o.pixelFormat=OP_PixelFormat::BGRA8Fixed;o.verticalFlip=flip;myDownload=top->downloadTexture(o,nullptr);if(myDownload){myPending=true;myPendingScale=scale;myPendingOutput=outputName;myLast=top->totalCooks;mySubmit++;l.unlock();myCond.notify_one();}}}
  Result r;{std::lock_guard<std::mutex>l(myMutex);r=myResult;}for(int i=0;i<2+myMaxValues;i++)out->channels[i][0]=0;if(active&&!r.values.empty()){out->channels[0][0]=1;out->channels[1][0]=(float)r.total;int n=std::min(myMaxValues,(int)r.values.size());for(int i=0;i<n;i++)out->channels[i+2][0]=r.values[i];}}
 void setupParameters(OP_ParameterManager*m,void*)override{OP_StringParameter top("Top");top.label="TOP";top.page="CoreML CHOP";m->appendTOP(top);OP_NumericParameter a("Active");a.label="Active";a.page="CoreML CHOP";a.defaultValues[0]=1;m->appendToggle(a);OP_StringParameter file("Modelfile");file.label="Model File";file.page="CoreML CHOP";m->appendFile(file);OP_NumericParameter reload("Reloadmodel");reload.label="Reload Model";reload.page="CoreML CHOP";m->appendPulse(reload);
  OP_StringParameter units("Computeunits");units.label="Compute Units";units.page="CoreML CHOP";units.defaultValue="all";const char*un[]={"all","cpugpu","cpuonly","cpuane"};const char*ul[]={"All (ANE + GPU + CPU)","CPU + GPU","CPU Only","CPU + Neural Engine"};m->appendMenu(units,4,un,ul);
  OP_StringParameter scaling("Scaling");scaling.label="Input Scaling";scaling.page="CoreML CHOP";scaling.defaultValue="scalefill";const char*sn[]={"scalefill","centercrop","scalefit"};const char*sl[]={"Scale Fill","Center Crop","Scale Fit"};m->appendMenu(scaling,3,sn,sl);
  OP_StringParameter name("Outputname");name.label="Output Feature Name";name.page="CoreML CHOP";m->appendString(name);OP_NumericParameter max("Maxvalues");max.label="Max Values";max.page="CoreML CHOP";max.defaultValues[0]=256;max.minSliders[0]=1;max.maxSliders[0]=1024;max.minValues[0]=1;max.maxValues[0]=65536;max.clampMins[0]=max.clampMaxes[0]=true;m->appendInt(max);OP_NumericParameter f("Flip");f.label="Flip Image Vertically";f.page="CoreML CHOP";f.defaultValues[0]=1;m->appendToggle(f);}
 void pulsePressed(const char*n,void*)override{if(!strcmp(n,"Reloadmodel")){std::lock_guard<std::mutex>l(myMutex);myForceReload=true;}}
 int32_t getNumInfoCHOPChans(void*)override{return 7;}void getInfoCHOPChan(int32_t i,OP_InfoCHOPChan*c,void*)override{const char*n[]={"executes","submits","analyzes","loaded","inference_ms","total_values","returned_values"};int total,returned;{std::lock_guard<std::mutex>l(myMutex);total=myResult.total;returned=(int)myResult.values.size();}float v[]={(float)myExec.load(),(float)mySubmit.load(),(float)myAnalyze.load(),myLoaded?1.f:0.f,myMs.load(),(float)total,(float)returned};c->name->setString(n[i]);c->value=v[i];}
 bool getInfoDATSize(OP_InfoDATSize*i,void*)override{i->rows=8;i->cols=2;i->byColumn=false;return true;}void getInfoDATEntries(int32_t r,int32_t,OP_InfoDATEntries*e,void*)override{std::lock_guard<std::mutex>l(myMutex);const char*k[]={"status","model","input","outputs","selected_output","shape","total_count","returned_count"};e->values[0]->setString(k[r]);std::string v;switch(r){case 0:v=myState.error.empty()?myState.status:myState.error;break;case 1:v=myRequestedPath;break;case 2:v=myState.input;break;case 3:v=myState.outputs;break;case 4:v=myResult.feature;break;case 5:v=myResult.shape;break;case 6:v=std::to_string(myResult.total);break;default:v=std::to_string(myResult.values.size());}e->values[1]->setString(v.c_str());}
 void getErrorString(OP_String*s,void*)override{std::lock_guard<std::mutex>l(myMutex);if(!myState.error.empty())s->setString(myState.error.c_str());}void getWarningString(OP_String*s,void*)override{std::lock_guard<std::mutex>l(myMutex);if(myState.status=="no model")s->setString("Set a Core ML model file");else if(myState.status=="compiling"||myState.status=="loading")s->setString("Loading model... (first ANE compile can take a while)");else if(!myRuntimeWarning.empty())s->setString(myRuntimeWarning.c_str());}
private:
 static NSURL*compiled(NSString*path,NSError**err){if([path hasSuffix:@".mlmodelc"])return[NSURL fileURLWithPath:path];NSFileManager*fm=[NSFileManager defaultManager];NSDictionary*a=[fm attributesOfItemAtPath:path error:nil];NSString*key=[NSString stringWithFormat:@"%@_%llu_%.0f",[[path lastPathComponent]stringByDeletingPathExtension],(unsigned long long)[a fileSize],[[a fileModificationDate]timeIntervalSince1970]];NSURL*dir=[[[fm URLsForDirectory:NSCachesDirectory inDomains:NSUserDomainMask]firstObject]URLByAppendingPathComponent:@"TDAppleML"];NSURL*cached=[[dir URLByAppendingPathComponent:key]URLByAppendingPathExtension:@"mlmodelc"];if([fm fileExistsAtPath:cached.path])return cached;NSURL*tmp=[MLModel compileModelAtURL:[NSURL fileURLWithPath:path]error:err];if(!tmp)return nil;[fm createDirectoryAtURL:dir withIntermediateDirectories:YES attributes:nil error:nil];if([fm moveItemAtURL:tmp toURL:cached error:nil])return cached;return tmp;}
 static std::string describe(NSDictionary<NSString*,MLFeatureDescription*>*d){NSMutableArray*p=[NSMutableArray array];for(NSString*n in d){MLFeatureDescription*f=d[n];if(f.type==MLFeatureTypeImage)[p addObject:[NSString stringWithFormat:@"%@:image %ldx%ld",n,(long)f.imageConstraint.pixelsWide,(long)f.imageConstraint.pixelsHigh]];else if(f.type==MLFeatureTypeMultiArray)[p addObject:[NSString stringWithFormat:@"%@:array %@",n,f.multiArrayConstraint.shape]];else[p addObject:[NSString stringWithFormat:@"%@:type %ld",n,(long)f.type]];}return str([p componentsJoinedByString:@", "]);}
 void load(const std::string&path,int units){@autoreleasepool{NSError*e=nil;NSURL*u=compiled([NSString stringWithUTF8String:path.c_str()],&e);VNCoreMLModel*vn=nil;std::string input,outputs,err;if(u){{std::lock_guard<std::mutex>l(myMutex);myState.status="loading";}MLModelConfiguration*c=[MLModelConfiguration new];c.computeUnits=units==1?MLComputeUnitsCPUAndGPU:units==2?MLComputeUnitsCPUOnly:MLComputeUnitsAll;if(units==3){if(@available(macOS 13.0,*))c.computeUnits=MLComputeUnitsCPUAndNeuralEngine;}MLModel*m=[MLModel modelWithContentsOfURL:u configuration:c error:&e];if(m){input=describe(m.modelDescription.inputDescriptionsByName);outputs=describe(m.modelDescription.outputDescriptionsByName);vn=[VNCoreMLModel modelForMLModel:m error:&e];}}if(!vn)err="Model load failed: "+str(e?e.localizedDescription:@"unknown error");std::lock_guard<std::mutex>l(myMutex);myModel=vn;myLoaded=vn!=nil;myState.status=myLoaded?"ready":"error";myState.error=err;myState.input=input;myState.outputs=outputs;}}
 void worker(){while(true){OP_SmartRef<OP_TOPDownloadResult>d;bool doLoad=false;std::string path,output;int units=0,scale=0;{std::unique_lock<std::mutex>l(myMutex);myCond.wait(l,[this]{return myQuit||myNeedLoad||myPending;});if(myQuit)return;if(myNeedLoad){doLoad=true;myNeedLoad=false;path=myRequestedPath;units=myRequestedUnits;myLoaded=false;myState.status="compiling";myState.error.clear();myRuntimeWarning.clear();}else{d=std::move(myDownload);output=myPendingOutput;scale=myPendingScale;myPending=false;myBusy=true;}}if(doLoad){load(path,units);continue;}Result r;std::string error;auto t=std::chrono::steady_clock::now();analyze(d,scale,output,r,error);myMs=std::chrono::duration<float,std::milli>(std::chrono::steady_clock::now()-t).count();myAnalyze++;{std::lock_guard<std::mutex>l(myMutex);if(!r.values.empty())myResult=std::move(r);myRuntimeWarning=error;myBusy=false;}}}
 static void flatten(MLMultiArray*a,int max,Result&r){r.total=(int)a.count;int n=std::min(max,r.total);r.values.resize(n);const void*p=a.dataPointer;for(int i=0;i<n;i++){switch(a.dataType){case MLMultiArrayDataTypeDouble:r.values[i]=((double*)p)[i];break;case MLMultiArrayDataTypeFloat32:r.values[i]=((float*)p)[i];break;case MLMultiArrayDataTypeFloat16:r.values[i]=(float)((__fp16*)p)[i];break;case MLMultiArrayDataTypeInt32:r.values[i]=(float)((int32_t*)p)[i];break;default:r.values[i]=0;}}NSMutableArray*d=[NSMutableArray array];for(NSNumber*x in a.shape)[d addObject:x.stringValue];r.shape=str([d componentsJoinedByString:@"x"]);}
 void analyze(OP_SmartRef<OP_TOPDownloadResult>&d,int scale,const std::string&wanted,Result&r,std::string&error){if(!d)return;void*data=d->getData();uint32_t w=d->textureDesc.width,h=d->textureDesc.height;if(!data||!w||!h)return;VNCoreMLModel*model;{std::lock_guard<std::mutex>l(myMutex);model=myModel;}if(!model)return;@autoreleasepool{CVPixelBufferRef p=nullptr;CVPixelBufferCreateWithBytes(nullptr,w,h,kCVPixelFormatType_32BGRA,data,(size_t)w*4,nullptr,nullptr,nullptr,&p);if(!p)return;VNCoreMLRequest*q=[[VNCoreMLRequest alloc]initWithModel:model];q.imageCropAndScaleOption=scale==1?VNImageCropAndScaleOptionCenterCrop:scale==2?VNImageCropAndScaleOptionScaleFit:VNImageCropAndScaleOptionScaleFill;VNImageRequestHandler*handler=[[VNImageRequestHandler alloc]initWithCVPixelBuffer:p options:@{}];NSError*e=nil;auto t=std::chrono::steady_clock::now();bool ok=[handler performRequests:@[q]error:&e];myMs=std::chrono::duration<float,std::milli>(std::chrono::steady_clock::now()-t).count();CVPixelBufferRelease(p);if(!ok){error=str(e.localizedDescription);return;}for(VNObservation*o in q.results)if([o isKindOfClass:[VNCoreMLFeatureValueObservation class]]){VNCoreMLFeatureValueObservation*f=(id)o;if(!wanted.empty()&&str(f.featureName)!=wanted)continue;if(f.featureValue.type==MLFeatureTypeMultiArray&&f.featureValue.multiArrayValue){r.feature=str(f.featureName);flatten(f.featureValue.multiArrayValue,myMaxValues,r);return;}}error=wanted.empty()?"No MLMultiArray output found":"Output feature not found: "+wanted;}}
 std::thread myThread;std::condition_variable myCond;std::mutex myMutex;bool myQuit=false,myPending=false,myBusy=false,myNeedLoad=false,myForceReload=false,myLoaded=false;OP_SmartRef<OP_TOPDownloadResult>myDownload;VNCoreMLModel*myModel=nil;State myState;Result myResult;std::string myRequestedPath,myPendingOutput,mySig,myRuntimeWarning;int myRequestedUnits=0,myPendingScale=0,myMaxValues=256;int64_t myLast=-1;std::atomic<uint64_t>myExec{0},mySubmit{0},myAnalyze{0};std::atomic<float>myMs{0};
};}
extern "C"{DLLEXPORT void FillCHOPPluginInfo(CHOP_PluginInfo*i){if(!i->setAPIVersion(CHOPCPlusPlusAPIVersion))return;i->customOPInfo.opType->setString("Coreml");i->customOPInfo.opLabel->setString("CoreML");i->customOPInfo.opIcon->setString("CML");if(i->customOPInfo.opHelpURL)i->customOPInfo.opHelpURL->setString("https://github.com/sygnalinc/TDAppleOps/blob/main/CoreMLCHOP/README.md");i->customOPInfo.authorName->setString("SYGNAL Inc.");
i->customOPInfo.majorVersion = 0;
i->customOPInfo.minorVersion = 9;i->customOPInfo.minInputs=0;i->customOPInfo.maxInputs=0;}DLLEXPORT CHOP_CPlusPlusBase*CreateCHOPInstance(const OP_NodeInfo*i){return new CoreMLCHOP(i);}DLLEXPORT void DestroyCHOPInstance(CHOP_CPlusPlusBase*i){delete static_cast<CoreMLCHOP*>(i);}}
