#import <Foundation/Foundation.h>
#include <atomic>
#include <string>
#include "CHOP_CPlusPlusBase.h"
#include "CPlusPlus_Common.h"
using namespace TD;
extern "C"{void*va_create(int32_t);void va_feed(void*,const float*,int32_t,double);int32_t va_poll(void*,char*,int32_t);void va_destroy(void*);}
namespace {
class VoiceActivityCHOP final:public CHOP_CPlusPlusBase{
public:VoiceActivityCHOP(const OP_NodeInfo*){}~VoiceActivityCHOP()override{if(mySession)va_destroy(mySession);}void getGeneralInfo(CHOP_GeneralInfo*g,const OP_Inputs*,void*)override{g->cookEveryFrameIfAsked=true;g->timeslice=false;}bool getOutputInfo(CHOP_OutputInfo*i,const OP_Inputs*,void*)override{i->numChannels=6;i->numSamples=1;i->startIndex=0;return true;}void getChannelName(int32_t i,OP_String*n,const OP_Inputs*,void*)override{const char*x[]={"speaking","onset","offset","start","end","duration"};n->setString(x[i]);}
 void execute(CHOP_Output*out,const OP_Inputs*in,void*)override{myExec++;bool active=in->getParInt("Active")!=0;int sensitivity=std::clamp(in->getParInt("Sensitivity"),0,2);if(active&&(!mySession||sensitivity!=mySensitivity)){if(mySession)va_destroy(mySession);mySession=va_create(sensitivity);mySensitivity=sensitivity;myLastOnsets=myLastOffsets=0;}const OP_CHOPInput*a=in->getInputCHOP(0);if(active&&mySession&&a&&a->numChannels&&a->numSamples){va_feed(mySession,a->getChannelData(0),a->numSamples,a->sampleRate);myFeeds++;}bool speaking=false;uint64_t onsets=0,offsets=0;double start=0,end=0,duration=0;myStatus=active?"starting":"inactive";if(mySession){char b[2048];va_poll(mySession,b,sizeof(b));@autoreleasepool{NSData*d=[NSData dataWithBytes:b length:strlen(b)];NSDictionary*j=[NSJSONSerialization JSONObjectWithData:d options:0 error:nil];if([j isKindOfClass:[NSDictionary class]]){NSString*s=j[@"status"];if(s)myStatus=s.UTF8String;speaking=[j[@"speaking"] boolValue];onsets=[j[@"onsets"] unsignedLongLongValue];offsets=[j[@"offsets"] unsignedLongLongValue];start=[j[@"start"] doubleValue];end=[j[@"end"] doubleValue];duration=[j[@"duration"] doubleValue];}}}out->channels[0][0]=active&&speaking;out->channels[1][0]=active&&onsets>myLastOnsets;out->channels[2][0]=active&&offsets>myLastOffsets;out->channels[3][0]=active?start:0;out->channels[4][0]=active?end:0;out->channels[5][0]=active?duration:0;myLastOnsets=onsets;myLastOffsets=offsets;}
 void setupParameters(OP_ParameterManager*m,void*)override{OP_NumericParameter a("Active");a.label="Active";a.page="Voice Activity";a.defaultValues[0]=1;m->appendToggle(a);OP_StringParameter s("Sensitivity");s.label="Sensitivity";s.page="Voice Activity";s.defaultValue="medium";const char*n[]={"low","medium","high"};const char*l[]={"Low","Medium","High"};m->appendMenu(s,3,n,l);}
 int32_t getNumInfoCHOPChans(void*)override{return 2;}void getInfoCHOPChan(int32_t i,OP_InfoCHOPChan*c,void*)override{c->name->setString(i?"feeds":"executes");c->value=i?myFeeds.load():myExec.load();}bool getInfoDATSize(OP_InfoDATSize*i,void*)override{i->rows=1;i->cols=2;i->byColumn=false;return true;}void getInfoDATEntries(int32_t,int32_t,OP_InfoDATEntries*e,void*)override{e->values[0]->setString("status");e->values[1]->setString(myStatus.c_str());}
private:void*mySession=nullptr;int mySensitivity=-1;uint64_t myLastOnsets=0,myLastOffsets=0;std::string myStatus="inactive";std::atomic<uint64_t>myExec{0},myFeeds{0};};}
extern "C"{DLLEXPORT void FillCHOPPluginInfo(CHOP_PluginInfo*i){if(!i->setAPIVersion(CHOPCPlusPlusAPIVersion))return;i->customOPInfo.opType->setString("Speechactivity");i->customOPInfo.opLabel->setString("Speech Activity");i->customOPInfo.opIcon->setString("SAC");i->customOPInfo.authorName->setString("TDAppleML");i->customOPInfo.minInputs=1;i->customOPInfo.maxInputs=1;}DLLEXPORT CHOP_CPlusPlusBase*CreateCHOPInstance(const OP_NodeInfo*i){return new VoiceActivityCHOP(i);}DLLEXPORT void DestroyCHOPInstance(CHOP_CPlusPlusBase*i){delete static_cast<VoiceActivityCHOP*>(i);}}
